---
- hosts: all
  become: true
  tasks:
    - name: Update repository index
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    
    - name: Update repository index
      yum:
        update_cache: yes
      when: ansible_distribution == "CentOS"



- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: CentOS_servers
  become: true
  roles:
    - CentOS_servers
